export const ADD_TODO = 'ADD_TODO';
export const CLEAR_TODOS = 'CLEAR_TODOS';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO_COMPLETED = 'TOGGLE_TODO_COMPLETED';
export const ADD_TODOS_FROM_LOCAL_STORE = 'ADD_TODOS_FROM_LOCAL_STORE';

